### ISSUE TITLE
No way out if auth key is entered incorrectly

### ISSUE THREAD

**Issue by dthree** [websitesfortrello/trelew#1]
I was mid getting an auth key, and I had pressed enter. It appears the app accepted a blank string as the auth key, and then crashed with invalid auth key:

```
trelew~$
Error: invalid token
    at Request._callback (/home/user/.nvm/versions/node/v4.0.0/lib/node_modules/trelew/node_modules/node-trello/lib/node-trello.js:88:13)
    at Request.self.callback (/home/user/.nvm/versions/node/v4.0.0/lib/node_modules/trelew/node_modules/node-trello/node_modules/request/request.js:373:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/home/user/.nvm/versions/node/v4.0.0/lib/node_modules/trelew/node_modules/node-trello/node_modules/request/request.js:1318:14)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/home/user/.nvm/versions/node/v4.0.0/lib/node_modules/trelew/node_modules/node-trello/node_modules/request/request.js:1266:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
```
After this, every time I start the app, it crashes again on the "invalid token" and doesn't give me a chance to enter a correct one.

**Comment by fiatjaf** [comment]
Haha, that's a big issue. Thank you.

If you want a quick fix, delete the `~/.trelew` directory.

**Comment by fiatjaf** [comment]
Solved by https://github.com/websitesfortrello/trelew/commit/3b2dc5d2805f100089f2fdfe351fff1f783beb93

**Comment by dthree** [comment]
Nice! :+1:
