### ISSUE TITLE
Error connecting

### ISSUE THREAD

**Issue by aharris88** [websitesfortrello/trelew#12]
After I pasted in my token from Trello, I got this error:

```
connected as aharris88
TypeError: Cannot read property 'toString' of undefined
    at module.exports (/usr/local/lib/node_modules/trelew/node_modules/pad/lib/index.js:22:14)
    at /usr/local/lib/node_modules/trelew/helpers.js:101:71
    at Array.map (native)
    at CommandInstance.listBoards (/usr/local/lib/node_modules/trelew/helpers.js:97:56)
    at /usr/local/lib/node_modules/trelew/index.js:410:24
    at process._tickCallback (node.js:382:9)
```

**Comment by fiatjaf** [comment]
You don't have a board with a blank name, do you?

**Comment by aharris88** [comment]
No, I don't.
