### ISSUE TITLE
tab autocompletion gives error

### ISSUE THREAD

**Issue by strages** [websitesfortrello/trelew#8]
gives me the following error

```
card taa

readline.js:924
            throw err;
            ^

TypeError: _.pluck is not a function
    at EventEmitter.session.getAutocomplete (/usr/local/lib/node_modules/trelew/node_modules/vorpal/lib/session.js:266:17)
    at EventEmitter.session.getKeypressResult (/usr/local/lib/node_modules/trelew/node_modules/vorpal/lib/session.js:215:12)
    at EventEmitter.vorpal._onKeypress (/usr/local/lib/node_modules/trelew/node_modules/vorpal/lib/vorpal.js:470:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/trelew/node_modules/vorpal/lib/vorpal.js:119:10)
    at emitOne (events.js:77:13)
    at Object.emit (events.js:169:7)
    at Object.ui._keypressHandler (/usr/local/lib/node_modules/trelew/node_modules/vorpal/lib/ui.js:263:10)
    at Prompt.inquirer.prompt.prompts.(anonymous function).onKeypress (/usr/local/lib/node_modules/trelew/node_modules/vorpal/lib/ui.js:112:14)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.next (/usr/local/lib/node_modules/trelew/node_modules/rx-lite/rx.lite.js:1535:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/usr/local/lib/node_modules/trelew/node_modules/rx-lite/rx.lite.js:1469:31)
```

**Comment by fiatjaf** [comment]
Did you get that more than once? Were you stress testing the app by pressing tab multiple times? I don't know what could have caused this, do you, @dthree? I feel that `_.pluck` should always be a function.

**Comment by dthree** [comment]
I just upgraded Vorpal's `lodash` dependency to `4.0`, and I didn't realize commands were deprecated in it.

I updated Vorpal to fix this, so just install the latest copy of Vorpal.

Sorry about that!
